### ISSUE TITLE
Capped / Max Strength Param

### ISSUE THREAD

**Issue by samuelgoddard** [Aminerman/vue-mouse-parallax#11]
Hey, thanks for the great plugin. I've stumbled across one slight bug, is it possible to pass in a max strength attribute, when i load my page, if my cursor is already over a parallax element (before it's actually rendered), when it finally renders it's all borked due to my cursor placement. It's fine once I move it and it seems to reset itself. It'd be ideal if i could "cap" the strength amount. If not how would you suggest approaching this?

**Comment by Aminerman** [comment]
Hello! Thank you for mentionning this issue. It has been fixed on the latest release. This problem shouldn't happen anymore and you don't need to cap the strength for that.
