### ISSUE TITLE
Cannot read property 'install' of undefined

### ISSUE THREAD

**Issue by imanaspaul** [Aminerman/vue-mouse-parallax#13]

**Comment by Aminerman** [comment]
Hello, can you give more context about this issue?

**Comment by winardidesign** [comment]
I also facing the same problem

Already add this to my main js file

import VueMouseParallax from 'vue-mouse-parallax'

Vue.use(VueMouseParallax)

In console log

Uncaught TypeError: Cannot read property 'install' of undefined
    at Function.Vue.use (app.js:23691)

**Comment by Aminerman** [comment]
Hi! The latest update fixed this. Install vue-kinesis instead of vue-mouse-parallax. There is a section in the readme that explains how to migrate from the old version.
