### ISSUE TITLE
Missing CSS classes to make parallax-element overlap

### ISSUE THREAD

**Issue by gluneau** [Aminerman/vue-mouse-parallax#18]
Could you provide the CSS to make parallax-element overlap?

It would help if you released the code you used to make the demo.

**Comment by Aminerman** [comment]
`parallax-element` are actually just normal DOM elements. You can add a class to them and give them a `position: absolute` and you can therefore make them overlap.
Does it help solving your issue?

**Comment by gluneau** [comment]
As soon as I use `position: absolute` everything stop moving.  No more parallax effect.  I'm missing some CSS magic somewhere.

**Comment by Aminerman** [comment]
My guess is that, if all your `parallax-element` are in `position: absolute`, therefore your `parallax-container` has a **width** and **height** equal to **0**. Therefore there can't be any movement as the `parallax-container` is the one that detects the mouse movement.
So depending on your case and the result you're trying to achieve you need to find a way to give your `parallax-container` a **width** and **height**.
