### ISSUE TITLE
movementX data variable is Infinity

### ISSUE THREAD

**Issue by Kexerval** [Aminerman/vue-mouse-parallax#5]
I tried to use `vue-mouse-parallax` inside of [`vue-carousel`](https://ssense.github.io/vue-carousel/) to apply parallax to the carousel slides. The `movementX` data value is set to `Infinity` and as a result, no CSS transforms are applied. Relevant HTML snippets below:

[Inspection of the ParallaxElement Vue component](https://cdn.discordapp.com/attachments/400812774667845663/531246888591294491/unknown.png)

HTML affected:
```
<Carousel
  :autoplay="true"
  :autoplayTimeout="5000"
  :perPage="1"
  :scrollPerPage="false"
  :paginationActiveColor="'#005e71'">
  <Slide>
    <img
      src="/assets/featured/attract/1.jpg"
      alt="snip">
  </Slide>
  <Slide>
    <parallax-container>
      <parallax-element
        :parallaxStrength="5"
        :type="'translation'">
      <img
        src="/assets/featured/attract/2.jpg"
        alt="snip">
      </parallax-element>
    </parallax-container>
  </Slide>
</Carousel>

**Comment by Aminerman** [comment]
Hello! I pushed a new version of the plugin. It should solve the issue. Let me know if you still stumble upon a problem.
