### ISSUE TITLE
problem on scroll down

### ISSUE THREAD

**Issue by Aryan-mor** [Aminerman/vue-mouse-parallax#9]
on mouse hover on item when scroll reaches the end  last items this problem

![untitled](https://user-images.githubusercontent.com/22844436/53284552-4f1f7200-376b-11e9-8fb4-739dbbcd41c5.png)
![untitled1](https://user-images.githubusercontent.com/22844436/53284551-4e86db80-376b-11e9-968c-bd9ae43f29af.png)

**Comment by Aminerman** [comment]
Hello, I pushed a new version of the plugin. This issue should be solved now.
